### ISSUE TITLE
[ERROR] info_requests#index (ActionView::Template::Error) "unknown status referred"

### ISSUE THREAD

**Issue by garethrees** [mysociety/asktheeu-theme#109]
```
An ActionView::Template::Error occurred in info_requests#index:

unknown status referred
app/models/info_request/state.rb:57:in `short_description'

-------------------------------
Request:
-------------------------------

* URL : https://www.asktheeu.org/en/alaveteli_pro/info_requests
* HTTP Method: GET
* IP address : REDACTED
* Parameters : {"controller"=>"alaveteli_pro/info_requests", "action"=>"index", "locale"=>"en"}
* Timestamp : 2020-06-04 15:37:22 +0200
* Rails root : /REDACTED/alaveteli-2020-06-02T16-17-57

-------------------------------
Session:
-------------------------------

* session id: [FILTERED]
* data: {"session_id"=>"REDACTED",
"locale"=>"en",
"user_id"=>4247,
"remember_me"=>true,
"post_redirect_token"=>"REDACTED",
"_csrf_token"=>"REDACTED"}

-------------------------------
Backtrace:
-------------------------------

app/models/info_request/state.rb:57:in `short_description'
app/views/alaveteli_pro/info_requests/_info_request.html.erb:20:in `_app_views_alaveteli_pro_info_requests__info_request_html_erb__1065734159428160599_70336905055980'
app/views/alaveteli_pro/info_requests/_request_list.html.erb:53:in `_app_views_alaveteli_pro_info_requests__request_list_html_erb___1594160175614322461_70336907098940'
app/views/alaveteli_pro/info_requests/index.html.erb:20:in `_app_views_alaveteli_pro_info_requests_index_html_erb__660419142130959692_70336910982000'
app/controllers/application_controller.rb:115:in `record_memory'
lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by garethrees** [comment]
Looks like the theme needs to define [`InfoRequest.theme_short_description`](https://github.com/mysociety/alaveteli/blob/develop/app/models/info_request/state.rb#L55), but [it doesn't](https://github.com/mysociety/asktheeu-theme/blob/6fa38656f0a4c97c3d1c0f02a74d399cb65bed8e/lib/customstates.rb).
