### ISSUE TITLE
[ERROR] info_requests#index (ActionView::Template::Error) "unknown status transferred"

### ISSUE THREAD

**Issue by garethrees** [mysociety/asktheeu-theme#110]
```
An ActionView::Template::Error occurred in info_requests#index:

unknown status transferred
app/models/info_request/state.rb:57:in `short_description'

-------------------------------
Request:
-------------------------------

* URL : https://www.asktheeu.org/en/alaveteli_pro/info_requests
* HTTP Method: GET
* Parameters : {"controller"=>"alaveteli_pro/info_requests", "action"=>"index", "locale"=>"en"}
* Timestamp : 2020-06-08 11:31:41 +0200
* Rails root : /REDACTED/alaveteli-2020-06-02T16-17-57

-------------------------------
Session:
-------------------------------

* session id: [FILTERED]
* data: {"session_id"=>"REDACTED",
"locale"=>"en",
"_csrf_token"=>"REDACTED",
"remember_me"=>true,
"user_id"=>3016,
"post_redirect_token"=>"REDACTED"}

-------------------------------
Backtrace:
-------------------------------

app/models/info_request/state.rb:57:in `short_description'
app/views/alaveteli_pro/info_requests/_info_request.html.erb:20:in `_app_views_alaveteli_pro_info_requests__info_request_html_erb__93623086187802258_69834370089500'
app/views/alaveteli_pro/info_requests/_request_list.html.erb:53:in `_app_views_alaveteli_pro_info_requests__request_list_html_erb___816051020440591747_69834374167720'
app/views/alaveteli_pro/info_requests/index.html.erb:20:in `_app_views_alaveteli_pro_info_requests_index_html_erb___1811845732724204113_69834375028840'
app/controllers/application_controller.rb:115:in `record_memory'
lib/strip_empty_sessions.rb:13:in `call'

```

**Comment by garethrees** [comment]
Same problem as https://github.com/mysociety/asktheeu-theme/issues/109
