### ISSUE TITLE
[ERROR] request_game#play (NoMethodError) "undefined method `where_old_unclassified'

### ISSUE THREAD

**Issue by lizconlan** [mysociety/asktheeu-theme#48]
```
A NoMethodError occurred in request_game#play:

  undefined method `where_old_unclassified' for #<Class:0x000000075f89d8>
  vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.22.2/lib/active_record/dynamic_matchers.rb:55:in `method_missing'


-------------------------------
Request:
-------------------------------

  * URL       : https://www.asktheeu.org/categorise/play
  * IP address: 94.8.97.221
  * Parameters: {"controller"=>"request_game", "action"=>"play"}
  * Rails root: /data/vhost/eu.alaveteli.org/alaveteli-2016-07-08T09-00-06
  * Timestamp : 2016-07-15 11:18:43 +0200

-------------------------------
Session:
-------------------------------

  * session id: [FILTERED]
  * data: {"session_id"=>"7ea2ba56fa663e97fdcbda00c2603359",
   "locale"=>"en",
   "remember_me"=>false,
   "_csrf_token"=>"DEHiy1+YUvUiWA3v3wnxiUmJ72UjhfBX/rc5bYJCgdM=",
   "request_game"=>2016-07-15 10:18:43 +0100}

-------------------------------
Environment:
-------------------------------

  * HTTP_ACCEPT                                    : text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
  * HTTP_ACCEPT_ENCODING                           : gzip
  * HTTP_ACCEPT_LANGUAGE                           : en-US,en;q=0.8
  * HTTP_COOKIE                                    : last_request_id=2148; _wdtk_cookie_session=BAh7CUkiD3Nlc3Npb25faWQGOgZFRkkiJTdlYTJiYTU2ZmE2NjNlOTdmZGNiZGEwMGMyNjAzMzU5BjsAVEkiC2xvY2FsZQY7AEZJIgdlbgY7AFRJIhByZW1lbWJlcl9tZQY7AEZGSSIQX2NzcmZfdG9rZW4GOwBGSSIxREVIaXkxK1lVdlVpV0EzdjN3bnhpVW1KNzJVamhmQlgvcmM1YllKQ2dkTT0GOwBG--58a51ed8ca4030eb0431e0e9eef61d0151f23466
  * HTTP_DNT                                       : 1
  * HTTP_HOST                                      : www.asktheeu.org
  * HTTP_UPGRADE_INSECURE_REQUESTS                 : 1
  * HTTP_USER_AGENT                                : Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36
  * HTTP_VERSION                                   : HTTP/1.1
  * HTTP_X_FORWARDED_FOR                           : 94.8.97.221
  * HTTP_X_FORWARDED_PROTO                         : https
  * HTTP_X_REAL_IP                                 : 94.8.97.221
  * HTTP_X_VARNISH                                 : 2111951461
  * ORIGINAL_FULLPATH                              : /categorise/play
  * PASSENGER_CONNECT_PASSWORD                     : [FILTERED]
  * PATH_INFO                                      : /categorise/play
  * QUERY_STRING                                   :
  * REMOTE_ADDR                                    : 94.8.97.221
  * REMOTE_PORT                                    : 38627
  * REQUEST_METHOD                                 : GET
  * REQUEST_URI                                    : /categorise/play
  * SCRIPT_NAME                                    :
  * SCRIPT_URI                                     : http://www.asktheeu.org/categorise/play
  * SCRIPT_URL                                     : /categorise/play
  * SERVER_NAME                                    : www.asktheeu.org
  * SERVER_PORT                                    : 80
  * SERVER_PROTOCOL                                : HTTP/1.1
  * SERVER_SOFTWARE                                : Apache/2.2.22 (Debian) mod_fastcgi/mod_fastcgi-SNAP-0910052141 Phusion_Passenger/5.0.29
  * action_controller.instance                     : request_game#play
  * action_dispatch.backtrace_cleaner              : #<Rails::BacktraceCleaner:0x000000075528f8>
  * action_dispatch.cookies                        : #<ActionDispatch::Cookies::CookieJar:0x007f98f84fd060>
  * action_dispatch.logger                         : #<ActiveSupport::TaggedLogging:0x000000023042b8>
  * action_dispatch.parameter_filter               : [:password, /RAW_POST_DATA/]
  * action_dispatch.remote_ip                      : 94.8.97.221
  * action_dispatch.request.content_type           :
  * action_dispatch.request.formats                : [text/html]
  * action_dispatch.request.parameters             : {"controller"=>"request_game", "action"=>"play"}
  * action_dispatch.request.path_parameters        : {:controller=>"request_game", :action=>"play"}
  * action_dispatch.request.query_parameters       : {}
  * action_dispatch.request.request_parameters     : {}
  * action_dispatch.request.unsigned_session_cookie: {"session_id"=>"7ea2ba56fa663e97fdcbda00c2603359", "locale"=>"en", "remember_me"=>false, "_csrf_token"=>"DEHiy1+YUvUiWA3v3wnxiUmJ72UjhfBX/rc5bYJCgdM="}
  * action_dispatch.request_id                     : ac38a7349d9e3ae928895fdbcba18385
  * action_dispatch.routes                         : #<ActionDispatch::Routing::RouteSet:0x00000005da25a0>
  * action_dispatch.secret_token                   : 3518a2f28ad3289fc9a1c76eddc6817d83472cc2d9812db1cc4c1dbe1f82fc0a436de5d4911b884c437184b93e06966a13087b692703808bdeeeca4410cfdbda5
  * action_dispatch.show_detailed_exceptions       : false
  * action_dispatch.show_exceptions                : true
  * newrelic.transaction_started                   : true
  * rack.errors                                    : #<IO:0x00000002063220>
  * rack.hijack                                    : #<Proc:0x007f98f85024c0@/usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:84 (lambda)>
  * rack.hijack?                                   : true
  * rack.input                                     : #<PhusionPassenger::Utils::TeeInput:0x007f98f85026a0>
  * rack.multiprocess                              : true
  * rack.multithread                               : false
  * rack.request.cookie_hash                       : {"last_request_id"=>"2148", "_wdtk_cookie_session"=>"BAh7CUkiD3Nlc3Npb25faWQGOgZFRkkiJTdlYTJiYTU2ZmE2NjNlOTdmZGNiZGEwMGMyNjAzMzU5BjsAVEkiC2xvY2FsZQY7AEZJIgdlbgY7AFRJIhByZW1lbWJlcl9tZQY7AEZGSSIQX2NzcmZfdG9rZW4GOwBGSSIxREVIaXkxK1lVdlVpV0EzdjN3bnhpVW1KNzJVamhmQlgvcmM1YllKQ2dkTT0GOwBG--58a51ed8ca4030eb0431e0e9eef61d0151f23466"}
  * rack.request.cookie_string                     : last_request_id=2148; _wdtk_cookie_session=BAh7CUkiD3Nlc3Npb25faWQGOgZFRkkiJTdlYTJiYTU2ZmE2NjNlOTdmZGNiZGEwMGMyNjAzMzU5BjsAVEkiC2xvY2FsZQY7AEZJIgdlbgY7AFRJIhByZW1lbWJlcl9tZQY7AEZGSSIQX2NzcmZfdG9rZW4GOwBGSSIxREVIaXkxK1lVdlVpV0EzdjN3bnhpVW1KNzJVamhmQlgvcmM1YllKQ2dkTT0GOwBG--58a51ed8ca4030eb0431e0e9eef61d0151f23466
  * rack.request.query_hash                        : {}
  * rack.request.query_string                      :
  * rack.run_once                                  : false
  * rack.session                                   : {"session_id"=>"7ea2ba56fa663e97fdcbda00c2603359", "locale"=>"en", "remember_me"=>false, "_csrf_token"=>"DEHiy1+YUvUiWA3v3wnxiUmJ72UjhfBX/rc5bYJCgdM=", "request_game"=>2016-07-15 10:18:43 +0100}
  * rack.session.options                           : {:path=>"/", :domain=>nil, :expire_after=>nil, :secure=>false, :httponly=>true, :defer=>false, :renew=>false, :secret=>"7c95304eed8b5619868642cd15635b4bae12a75655db3a25fbfa46018694", :coder=>#<Rack::Session::Cookie::Base64::Marshal:0x0000000679e978>, :id=>"7ea2ba56fa663e97fdcbda00c2603359"}
  * rack.url_scheme                                : http
  * rack.version                                   : [1, 2]

  * Process: 32697
  * Server : mastodon

-------------------------------
Backtrace:
-------------------------------

  vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.22.2/lib/active_record/dynamic_matchers.rb:55:in `method_missing'
  lib/themes/asktheeu-theme/lib/controller_patches.rb:70:in `play'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/abstract_controller/base.rb:167:in `process_action'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_controller/metal/rendering.rb:10:in `process_action'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.22.2/lib/active_support/callbacks.rb:602:in `block in _run__543742578102551032__process_action__2023904174494975190__callbacks'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.22.2/lib/active_support/callbacks.rb:215:in `block in _conditional_callback_around_1362'
  app/controllers/application_controller.rb:105:in `record_memory'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.22.2/lib/active_support/callbacks.rb:214:in `_conditional_callback_around_1362'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.22.2/lib/active_support/callbacks.rb:601:in `_run__543742578102551032__process_action__2023904174494975190__callbacks'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.22.2/lib/active_support/callbacks.rb:405:in `__run_callback'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.22.2/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.22.2/lib/active_support/callbacks.rb:81:in `run_callbacks'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/abstract_controller/callbacks.rb:17:in `process_action'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_controller/metal/rescue.rb:29:in `process_action'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.22.2/lib/active_support/notifications.rb:123:in `block in instrument'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.22.2/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.22.2/lib/active_support/notifications.rb:123:in `instrument'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
  vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.22.2/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:30:in `block in process_action'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:362:in `perform_action_with_newrelic_trace'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:29:in `process_action'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/abstract_controller/base.rb:121:in `process'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/abstract_controller/rendering.rb:45:in `process'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_controller/metal.rb:203:in `dispatch'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_controller/metal.rb:246:in `block in action'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_dispatch/routing/route_set.rb:73:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_dispatch/routing/route_set.rb:36:in `call'
  vendor/bundle/ruby/1.9.1/gems/journey-1.0.4/lib/journey/router.rb:68:in `block in call'
  vendor/bundle/ruby/1.9.1/gems/journey-1.0.4/lib/journey/router.rb:56:in `each'
  vendor/bundle/ruby/1.9.1/gems/journey-1.0.4/lib/journey/router.rb:56:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_dispatch/routing/route_set.rb:608:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/rack/browser_monitoring.rb:32:in `traced_call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/1.9.1/gems/exception_notification-3.0.1/lib/exception_notifier.rb:41:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/1.9.1/gems/rack-1.4.7/lib/rack/etag.rb:23:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/1.9.1/gems/rack-1.4.7/lib/rack/conditionalget.rb:25:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_dispatch/middleware/head.rb:14:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_dispatch/middleware/flash.rb:242:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/1.9.1/gems/rack-1.4.7/lib/rack/session/abstract/id.rb:210:in `context'
  vendor/bundle/ruby/1.9.1/gems/rack-1.4.7/lib/rack/session/abstract/id.rb:205:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_dispatch/middleware/cookies.rb:341:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/1.9.1/gems/rack-ssl-1.3.4/lib/rack/ssl.rb:27:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  lib/strip_empty_sessions.rb:13:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.22.2/lib/active_record/query_cache.rb:64:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.22.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.22.2/lib/active_support/callbacks.rb:405:in `_run__3478024054698046046__call__126418583845643612__callbacks'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.22.2/lib/active_support/callbacks.rb:405:in `__run_callback'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.22.2/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.22.2/lib/active_support/callbacks.rb:81:in `run_callbacks'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/1.9.1/gems/railties-3.2.22.2/lib/rails/rack/logger.rb:32:in `call_app'
  vendor/bundle/ruby/1.9.1/gems/railties-3.2.22.2/lib/rails/rack/logger.rb:16:in `block in call'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.22.2/lib/active_support/tagged_logging.rb:22:in `tagged'
  vendor/bundle/ruby/1.9.1/gems/railties-3.2.22.2/lib/rails/rack/logger.rb:16:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_dispatch/middleware/request_id.rb:22:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/1.9.1/gems/rack-1.4.7/lib/rack/methodoverride.rb:21:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/1.9.1/gems/rack-1.4.7/lib/rack/runtime.rb:17:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.22.2/lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/1.9.1/gems/rack-1.4.7/lib/rack/lock.rb:15:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.22.2/lib/action_dispatch/middleware/static.rb:83:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/1.9.1/gems/rack-utf8_sanitizer-1.3.0/lib/rack/utf8_sanitizer.rb:15:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  vendor/bundle/ruby/1.9.1/gems/railties-3.2.22.2/lib/rails/engine.rb:484:in `call'
  vendor/bundle/ruby/1.9.1/gems/railties-3.2.22.2/lib/rails/application.rb:231:in `call'
  vendor/bundle/ruby/1.9.1/gems/railties-3.2.22.2/lib/rails/railtie/configurable.rb:30:in `method_missing'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:152:in `accept_and_process_next_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
```

**Comment by lizconlan** [comment]
The controller controller [attempts to call `InfoRequest.where_old_unclassified`](https://github.com/mysociety/asktheeu-theme/blob/master/lib/controller_patches.rb#L70-L73) which was introduced in [edd3760](https://www.github.com/mysociety/alaveteli/commit/edd3760) and is not yet in a release branch.

Quickest fix will be to change it to use `@missing = InfoRequest.count_old_unclassified(:conditions => ["prominence = 'normal'"])` instead
